name: elastik_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  provider: ^6.1.1
  intl: ^0.20.2
  multi_dropdown: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ET_logo_text.png
    - assets/images/ET_logo.jpg
    - lib/data/contributions.json
    - lib/data/daily_news.json
    - lib/data/events.json
    - lib/data/stock_items.json
    - lib/data/users.json
    - lib/data/wfo_schemas.json